config/routes.rb
Rails.application.routes.draw do
  root 'vocabularies#index'
  resources :vocabularies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
      {id: 1, name: 'HTML'}, {id: 2, name: 'CSS'}, {id: 3, name: 'Ruby'}, {id: 4, name: 'JavaScript'}, {id: 5, name: 'linux'}, {id: 6, name: 'RSpec'}, {id: 7, name: 'C++'}, {id: 8, name: 'PHP'}, {id: 9, name: 'java'}, {id: 10, name: 'Python'}, {id: 11, name: 'その他'}
  ]
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  def index
    @vocabularies = Vocabulary.all.order('title ASC')
    @random = Vocabulary.order("RAND()").limit(5)
    @html = Vocabulary.where(genre_id: 1)
    @css = Vocabulary.where(genre_id: 2)
    @ruby = Vocabulary.where(genre_id: 3)
    @javascript = Vocabulary.where(genre_id: 4)
    @linux = Vocabulary.where(genre_id: 5)
    @rspec = Vocabulary.where(genre_id: 6)
    @c = Vocabulary.where(genre_id: 7)
    @php = Vocabulary.where(genre_id: 8)
    @java = Vocabulary.where(genre_id: 9)
    @python = Vocabulary.where(genre_id: 10)
    @other = Vocabulary.where(genre_id: 11)
  end

  def new
    @vocabulary = Vocabulary.new
  end

  def create
    @vocabulary = Vocabulary.new(vocabulary_params)
    if @vocabulary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @vocabulary = Vocabulary.find(params[:id])
  end

  def edit
    @vocabulary = Vocabulary.find(params[:id])
  end

  def destroy
    vocabulary = Vocabulary.find(params[:id])
    vocabulary.destroy
    redirect_to root_path
  end

  def update
    vocabulary = Vocabulary.find(params[:id])
    vocabulary.update(vocabulary_params)
    redirect_to root_path
  end

  private
  def vocabulary_params
    params.require(:vocabulary).permit(:title, :content, :genre_id)#.merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VocabularyBook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/vocabularies/edit.html.haml
.form
  = form_for @vocabulary do |f|
    .title
      = f.label :title, "タイトル"
      = f.text_field :title, class: "text_field"
    .content
      = f.label :content, "詳細"
      = f.text_area :content, class: "text_area"
    .genre
      = f.label :genre_id, "ジャンル"
      = f.collection_select :genre_id, Genre.all, :id, :name, prompt: "---", required: ""
    = f.submit "更新"
  = link_to '削除', @vocabulary, method: :delete
  = link_to '戻る', root_path

app/views/vocabularies/index.html.haml
.wrapper
  .header
    .title
      %h1単語帳
  .main
    .new
      = link_to "新規登録", new_vocabulary_path
    .remember
      %h4 復習単語
      -@random.each do |r|
        = link_to "#{r.title}", vocabulary_path(r.id)
    .lists
      .list
        %h3 HTML
        %h4 登録数：#{@html.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 1
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 CSS
        %h4 登録数：#{@css.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 2
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 Ruby
        %h4 登録数：#{@ruby.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 3
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 JavaScript
        %h4 登録数：#{@javascript.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 4
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 linux
        %h4 登録数：#{@linux.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 5
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 RSpec
        %h4 登録数：#{@rspec.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 6
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 C
        %h4 登録数：#{@c.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 7
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 PHP
        %h4 登録数：#{@php.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 8
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 Java
        %h4 登録数：#{@java.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 9
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 Python
        %h4 登録数：#{@python.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 10
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"
      .list
        %h3 その他
        %h4 登録数：#{@other.count}
        - @vocabularies.each do |v|
          -if v.genre_id == 11
            = link_to "#{v.title}", vocabulary_path(v.id), class: "word"

app/views/vocabularies/new.html.haml
.form
  = form_for @vocabulary do |f|
    .title
      = f.label :title, "タイトル"
      = f.text_field :title, class: "text_field"
    .content
      = f.label :content, "詳細"
      = f.text_area :content, class: "text_area"
    .genre
      = f.label :genre_id, "ジャンル"
      = f.collection_select :genre_id, Genre.all, :id, :name, prompt: "---", required: ""
    = f.submit "登録"

app/views/vocabularies/show.html.haml
.show
  .title
    %h4 タイトル
    = @vocabulary.title
  .content
    %h4 説明
    = @vocabulary.content
  .genre
    %h4 ジャンル
    = @vocabulary.genre.name
  .link
    = link_to '編集', edit_vocabulary_path(@vocabulary)
    = link_to '削除', @vocabulary, method: :delete
    = link_to '戻る', root_path